/*
 * TestClassTest.java
 * JUnit based test
 *
 * Created on Date
 */

package org.netbeans.test.junit.testcreation.test;

import junit.framework.TestCase;
import junit.framework.*;
import java.util.ArrayList;

/**
 *
 * @author Tester
 */
public class TestClassTest extends TestCase {
    
    public TestClassTest(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    public void testAdd() {
        System.out.println("add");
        
        int a = 0;
        int b = 0;
        TestClass instance = new TestClass();
        
        int expResult = 0;
        int result = instance.add(a, b);
        assertEquals(expResult, result);
        
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }

    public void testArrayListCount() {
        System.out.println("arrayListCount");
        
        ArrayList a = null;
        TestClass instance = new TestClass();
        
        int expResult = 0;
        int result = instance.arrayListCount(a);
        assertEquals(expResult, result);
        
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }

    public void testSqr() {
        System.out.println("sqr");
        
        double a = 0.0;
        TestClass instance = new TestClass();
        
        double expResult = 0.0;
        double result = instance.sqr(a);
        assertEquals(expResult, result);
        
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }

    public void testThirdPow() {
        System.out.println("thirdPow");
        
        double a = 0.0;
        
        double expResult = 0.0;
        double result = TestClass.thirdPow(a);
        assertEquals(expResult, result);
        
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }
    
}

