<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="." tests="6" assertions="5" failures="3" errors="1" time="0.063556">
    <testsuite name="Calculator2Test" file="/home/gapon/NetBeansProjects/PhpProject01/tests/hola/Calculator2Test.php" tests="1" assertions="1" failures="0" errors="0" time="0.010951">
      <testcase name="testAdd" class="Calculator2Test" file="/home/gapon/NetBeansProjects/PhpProject01/tests/hola/Calculator2Test.php" line="43" assertions="1" time="0.010951"/>
    </testsuite>
    <testsuite name="NoTestClassTest" file="/home/gapon/NetBeansProjects/PhpProject01/tests/NoTestClassTest.php" tests="0" assertions="0" failures="0" errors="0" time="0.000000"/>
    <testsuite name="CalculatorTest" file="/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php" tests="5" assertions="4" failures="3" errors="1" time="0.052605">
      <testcase name="testAdd" class="CalculatorTest" file="/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php" line="43" assertions="1" time="0.010114"/>
      <testcase name="testAdd2" class="CalculatorTest" file="/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php" line="54" assertions="1" time="0.009994">
        <failure type="PHPUnit_Framework_ExpectationFailedException">testAdd2(CalculatorTest)
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ -1,3 +1 @@
-MyObject Object
-(
-)
+77
\ Chybi znak konce radku na konci souboru


/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php:56
</failure>
      </testcase>
      <testcase name="testAdd3" class="CalculatorTest" file="/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php" line="62" assertions="1" time="0.012491">
        <failure type="PHPUnit_Framework_ExpectationFailedException">testAdd3(CalculatorTest)
my expected message
Failed asserting that two strings are equal.
expected string &lt;hello&gt;
difference      &lt; x???&gt;
got string      &lt;hi&gt;

/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php:64
</failure>
      </testcase>
      <testcase name="testAdd4" class="CalculatorTest" file="/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php" line="70" assertions="1" time="0.010514">
        <failure type="PHPUnit_Framework_ExpectationFailedException">testAdd4(CalculatorTest)
Failed asserting that &lt;integer:2&gt; matches expected value &lt;integer:3&gt;.

/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php:75
</failure>
      </testcase>
      <testcase name="testAdd5" class="CalculatorTest" file="/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php" line="78" assertions="0" time="0.009492">
        <error type="Exception">testAdd5(CalculatorTest)
Exception: my exception

/home/gapon/NetBeansProjects/PhpProject01/src/Calculator.php:13
/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php:82
</error>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
